project:
  type: book

book:
  title: "Introduction to programming for data science"
  subtitle: "STAT 201"
  author: "Arvind Krishna"
  date: "9/20/2022"
  chapters:
    - index.qmd
    - Introduction to Jupyter Notebooks and programming in python.ipynb
    - data_structures.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



