project:
  type: book
  output-dir: docs


book:
  title: "Introduction to programming for data science"
  subtitle: "STAT 201 Winter 2025"
  #author: "Arvind Krishna"
  date: "1/7/2025"
  
  sidebar:
    search: true
    logo: "NU_Stat_logo.png"
    logo-href: "https://statistics.northwestern.edu/"
    
  chapters:
    - index.qmd
    - part: "Getting started: Coding environment"
      chapters:
        - venv_setup.ipynb
    - part: "Python"
      chapters:
        #- Introduction to Jupyter Notebooks and programming in python.ipynb
        - Variable_expressions_statements.ipynb
        - Control flow.ipynb
        - functions2.ipynb
        - data_structures.ipynb
        - python_iterable.ipynb
        - classes.ipynb
    - part: "R"
      chapters:
        - Variable_expressions_statements-R.qmd
        - control_flow.qmd
        - control_flow2.qmd 
        - robjects.qmd
        - data_structures_r.qmd
        #- recursion.qmd
  appendices: 
    - template_A01_WI25.ipynb
    - template_A02_WI25.ipynb
    - template_A03_WI25.ipynb
    - template_A04_WI25.ipynb
    - template_A05_WI25.qmd
    - Datasets.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



